### ISSUE TITLE
cmake modorganizer failed - Qt5WebEngine not found

### ISSUE THREAD

**Issue by Holt59** [LePresidente/modorganizer-umbrella#14]
The task `cmake modorganizer` keeps failing, with the following message in `stderr.log`:

> CMake Error at src/CMakeLists.txt:239 (FIND_PACKAGE):
 By not providing "FindQt5WebEngineWidgets.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Qt5WebEngineWidgets", but CMake did not find one.
>
 > Could not find a package configuration file provided by
  "Qt5WebEngineWidgets" with any of the following names:
>
> Qt5WebEngineWidgetsConfig.cmake
>   qt5webenginewidgets-config.cmake
>
>  Add the installation prefix of "Qt5WebEngineWidgets" to CMAKE_PREFIX_PATH
  or set "Qt5WebEngineWidgets_DIR" to a directory containing one of the above
  files.  If "Qt5WebEngineWidgets" provides a separate development package or
  SDK, be sure it has been installed.

Don't know if this is the problem but I have no `Qt5WebEngine.lib` inside `build/qt5/lib`, so maybe the Qt5WebEngine lib was not built?

**Comment by Holt59** [comment]
Any news on this? I am trying to find a fix but since I am not clear with the building process, I am stuck...

**Comment by LePresidente** [comment]
make sure you have https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk installed,  If i remember correctly it is a requirement for QTWebEngine

**Comment by LePresidente** [comment]
Ok i have updated the readme to include it as a dependency though umbrella currently won't check itself if it is installed.
