### ISSUE TITLE
Need to stash git repository manually when updating

### ISSUE THREAD

**Issue by Holt59** [LePresidente/modorganizer-umbrella#15]
I went back to this project after a week, and the builder tried to update all git repository, unfortunately it failed on a lots because I had "local changes" - I did not make these changes manually, these were made by `unimake` automatically the last time I tried to build.

Is this normal? I had to stash every change manually, which is quite painful, especially when a lots of repository are affected...

**Comment by LePresidente** [comment]
Not sure, though i can't reproduce my end.

**Comment by SuperSandro2000** [comment]
I think I know what he means. The ts files get sometimes updated for no reason.
