### ISSUE TITLE
Unimake compile error

### ISSUE THREAD

**Issue by CptMcSplody** [LePresidente/modorganizer-umbrella#16]
Installing collected packages: pyparsing, pydot
  Running setup.py install for pydot ... done
Successfully installed pydot-1.2.3 pyparsing-2.2.0
failed to set up environment (returncode 0):
Traceback (most recent call last):
  File "C:\modorganizer-umbrella-master\unimake.py", line 318, in <module>
    exitcode = main()
  File "C:\modorganizer-umbrella-master\unimake.py", line 250, in main
    init_config(args)
  File "C:\modorganizer-umbrella-master\unimake.py", line 225, in init_config
    if 'PYTHON' not in config['__environment']:
TypeError: argument of type 'bool' is not iterable

Cant seem to get it to build, checked my environment paths and its fine. using version 2.7.14 of python if it makes any difference

**Comment by CptMcSplody** [comment]
okay figure its something to do with visual studio, will continue trying to fix

**Comment by LePresidente** [comment]
No, I'm little confused how you hit this error in the first place

config['__environment'] is your system environment after running vcvarsall.bat from Visual studio. If the environment variable PYTHON doesn't exists it should use the executable "python.exe" that you called unimake.py with

**Comment by CptMcSplody** [comment]
yeah not sure either, tried tannins version and it works.

Tried yours on another system, got this error.

  Running setup.py install for pydot ... done
Successfully installed pydot-1.2.3 pyparsing-2.2.0
Traceback (most recent call last):
  File "C:\modorganizer-umbrella-master\unimake.py", line 320, in <module>
    exitcode = main()
  File "C:\modorganizer-umbrella-master\unimake.py", line 278, in main
    manager.enable_all(build_graph)
  File "C:\modorganizer-umbrella-master\unibuild\manager.py", line 61, in enable_all
    for node in graph.nodes_iter():
AttributeError: 'DiGraph' object has no attribute 'nodes_iter'

**Comment by LePresidente** [comment]
What command you calling e.g python.exe unimake.py args

**Comment by CptMcSplody** [comment]
with adm, have tried with just unimake.py. no args & unimake.py -d "C:/build" & -unimake.py -d "f:/build"
same error.

**Comment by LePresidente** [comment]
One sec, I can reproduce let me fix quickly and push a fix.

**Comment by CptMcSplody** [comment]
no worries still getting it after reinstall of python and fresh build.

**Comment by LePresidente** [comment]
Pull my changes though. Its fixed

**Comment by CptMcSplody** [comment]
okay will give it a go

**Comment by CptMcSplody** [comment]
Works - Thanks
