### ISSUE TITLE
Troubleshoot Building process (Unable to find vcvarsall.bat, please make sure you have 'Common C++ tools' Installed)

### ISSUE THREAD

**Issue by Nik-Lz** [LePresidente/modorganizer-umbrella#21]
Trying to build this unbelievable program. Why you want us to build Python and the QT monster is beyond me. I already have all these programs. Why you simply don't tell us to install these programs and just compile your own program **only** (MO2), as it happens in many other cases. No need to compile EVERYTHING. Anyway.  

My System:
Desktop Win8.1 x86_64 - all latest updates installed
Python 2.7.13 x64
QT 5.9 
all the other dependencies you mentioned are already working properly on my machine
Visual Studio 2015 Community - with all common C++ tools and the Windows 10 SDK (10.0.10240). 

Followed your instructions [here](http://forum.step-project.com/topic/12538-wip-how-to-build-modorganizer-using-modorganizer-umbrella)

Note that i cloned **this** repository (`git clone https://github.com/LePresidente/modorganizer-umbrella`). 

My error is: 

`Unable to find vcvarsall.bat, please make sure you have 'Common C++ tools' Installed` 

I clearly have the Common C++ tools installed. 

What i tried: 

1. Since we are trying to build python 2.7 we've got to supply the environment variables as done by that file (vcvarsall.bat). For me this file is at "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat". Even if i run it on the same cmd same problem persists. 

2. Tried with admin cmd too. 

3. I installed the Visual Studio C++ compiler for Python 2.7 (check [here](https://stackoverflow.com/questions/27670365/python-pip-install-error-unable-to-find-vcvarsall-bat-tried-all-solutions) ). 

I do not have the 7za 7zip command line utility. Are you positive that we need it (found it only [here](https://mgxp.blogspot.gr/2016/04/7-zip-7za-command-line-zip-tool.html)?

All failed. What else can i do? 

Please advice. Thanks.

**Comment by CptMcSplody** [comment]
have you tried this? https://pypi.python.org/pypi/setuptools

source https://blogs.msdn.microsoft.com/pythonengineering/2016/04/11/unable-to-find-vcvarsall-bat/

**Comment by Nik-Lz** [comment]
I have managed to build it. Check the discord servers and do not run vcvarsall, as the build program runs it itself. You also need MSVC 2017. Follow instructions very carefully. Admittedly i have never before had so much trouble in building a program.
