### ISSUE TITLE
cygwin and icu not getting installed during build

### ISSUE THREAD

**Issue by Helidoc65** [LePresidente/modorganizer-umbrella#24]
With may last download and build of the project both Cygwin and icu do not get built/installed and compiled, the build complains about icudt59.dll, icuin59.dll and icuuc59.dll not existing (due to the lack of install) so It can't transfer them. Build does complete, although there are things missing in the install directory and I do not know at this point how buggy the build will be without those two repos. I can see from the /unibuild/projects/ that icu.py and Cygwin.py never get touched by the build program.

**Comment by Helidoc65** [comment]
Install was depreciated from qt5.py and not restored to makefile.uni.py at the same time as openssl, restored to makefile.uni.py in front of qt5 call out and testing new build.

**Comment by CptMcSplody** [comment]
You don't need icu, something has failed in your setup. Yes that can happen. 
What version of vs are you running?

**Comment by CptMcSplody** [comment]
Yeah manually adding them fixed missing QTwindows dlls for some reason...

**Comment by Helidoc65** [comment]
I'm using MSVS and I ran across this [https://wiki.qt.io/Compiling-ICU-with-MSVC](url) I also ran across the precompiled as well during my research from npcglib's site, I have his dll's to plug and play if needed as a last resort for a build although I'm attempting to fix the umbrella so it will build on it's own. During my research I had noticed from ICU's page.. "The .tgz file cannot be used to build with Cygwin/MSVC" bug #13139 [http://bugs.icu-project.org/trac/ticket/13139](url) which the build calls for so I'm doing another build from the zip source and see where that leads me.

**Comment by CptMcSplody** [comment]
MSVS2013 branch uses cygwin build I think

**Comment by Helidoc65** [comment]
I'm using MSVS2015 Cygwin is just one way to build ICU. After further research it seems that QT comes with it's own version of ICU which it uses for it's webengine qt/resources/icudtl.dat and Chromium , after they began to phase out the webkit.

**Comment by Helidoc65** [comment]
Going to close this, was able to successfully build the whole project (was adding Cygwin and ICU back in the build for a stand alone under the umbrella) although I suspect both can be pulled with some code clean up with the updates to QT and it's conversion to the webengine and phase out of the webkit. As it turns out ICU with this bug The .tgz file cannot be used to build with Cygwin/MSVC" bug #13139 http://bugs.icu-project.org/trac/ticket/13139 made the source file unusable. The zip source file had to be converted to be usable.
