### ISSUE TITLE
QT cmake files - QTWidget not Found.

### ISSUE THREAD

**Issue by CptMcSplody** [LePresidente/modorganizer-umbrella#25]
The Cmake for modorganizer detects QTCore, but not QTWidgets and son on.
Have to manually add the path to the cmake cache as a work around.
Will try and make a fix once I have built Umbrella & ModOrganizer Completely

**Comment by Helidoc65** [comment]
I ran into this same issue with the preinstalled QT adding D:\MO2\Qt\5.9.2\msvc2015_64\bin as an example to your path and under system variables adding QTDIR for name  and D:\MO2\Qt\5.9.2\msvc2015_64 for value got rid of most of those issues for me.
