### ISSUE TITLE
Loot Version

### ISSUE THREAD

**Issue by Dave811** [LePresidente/modorganizer-umbrella#48]
Hey,

i found a problem in the config file

The wrong part: "'loot_commit': 'gec946b', # loot commit"
You forgot the 5 after the b.
So now it looks like "'loot_commit': 'gec946b5', # loot commit"

**Comment by Silarn** [comment]
Yeah, I meant to point this out. My own umbrella is tailored to my repos so I didn't push a correction.

**Comment by SuperSandro2000** [comment]
Will be fixed with the next bigger update.
